

supabase:

  provider:
    name: discord
    expire_token: 172800 # 2 days
    store_unique_by_id: true

  dev:
    url: https://wnnjduqkmchhdgqefssp.supabase.co
    anon_public_key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndubmpkdXFrbWNoaGRncWVmc3NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDk1MzU3ODAsImV4cCI6MjAyNTExMTc4MH0.HNuIJh-NALAu3o8LrEKIAskm2qSS-P5K4jfB4kAznYM
    secret_service: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndubmpkdXFrbWNoaGRncWVmc3NwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcwOTUzNTc4MCwiZXhwIjoyMDI1MTExNzgwfQ.wby8xC3cjSueeNjHoeXQrscYc9DNTCBz0Yo42o5YoxY
  prod:
    url: https://wnnjduqkmchhdgqefssp.supabase.co
    anon_public_key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndubmpkdXFrbWNoaGRncWVmc3NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDk1MzU3ODAsImV4cCI6MjAyNTExMTc4MH0.HNuIJh-NALAu3o8LrEKIAskm2qSS-P5K4jfB4kAznYM
    secret_service: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndubmpkdXFrbWNoaGRncWVmc3NwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcwOTUzNTc4MCwiZXhwIjoyMDI1MTExNzgwfQ.wby8xC3cjSueeNjHoeXQrscYc9DNTCBz0Yo42o5YoxY

server:
  port: 3001
  host: "localhost"
  api_path: "api"

  bandwith_limit: "1000mb"
  cors: {
    origin: "*"
  }
  url_encoded: true
  prod_api_url: "https://sentinelmod.com"

security:
  # api_password: "HV3unLo!PxPvHpmm$@5qM5XJpxXb7pxVv#pXn!DYXFibch#An9**n5!cuUg2Fz*cR5f@!LgMWKFvZFWozh3!J*&xshARCw4qUYWbRsgDir!Cc3s!K@eL$7LMiFpXd@VA"

  ratelimit:
    enabled: false

    # Scoring
    high_z_score: 1.96 # how far above average the requests are 
    low_z_score: -1.96 # how far below average the requests are 
    
    # Collecting how many requests each individual user makes per hour
    collection:

      - key: "hourly-request-collector"
        elapsed_duration: 3600 # 1 hour
        unique_to_request: true

      - key: "daily-request-collector"
        elapsed_duration: 3600
        unique_to_request: false
    

  end_end_auth:
    endpoints:
      # - "dashboard"

    restrict:
      error_found: true
      no_user_found: true
      invalid_user_id: true
      no_user_id_found: true

database:

  postgresql:

    dev:
      host: "localhost"
      port: 5432
      database: "nomobot"
      user: "postgres"
      password: "BS103261"
      url: 
    prod:
      host: "localhost"
      port: 5432
      database: "nomobot"
      user: "postgres"
      password: "BS103261"

  redis:
    dev:
      port: 6379
      host: localhost
      url: null
    prod:
      port: 6379
      host: localhost
      url: null
