name: Main

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:

    runs-on: sentinel
  
    steps:
    # - uses: actions/checkout@v3
    # - name: Copy config directory to bot and api directories
    #   run: |
    #     set -e
    #     cp -r ./config ./bot/
    #     cp -r ./config ./api/
    #     cp -r ./config ./website/
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        set -e

        cp -r config api
        cp -r config dashboard

        docker build --tag nb-redis ./redis
        docker build --tag nb-api ./api
        docker build --tag nb-site ./dashboard
        docker build --tag nb-proxy ./proxy

  deploy:

    runs-on: nomobot
    needs: build

    steps:
      - uses: actions/checkout@v3
      - name: Launch docker containers
        run: |
          set -e
          echo "Starting the docker containers"
          docker rm -f redis && docker run -d --restart always --net host --name redis nb-redis
          sleep 5
          docker rm -f api && docker run -d --restart always --net host --name api nb-api
          docker rm -f dashboard && docker run -d --restart always --net host --name dashboard nb-site
          docker rm -f proxy && docker run -d --restart always --net host --name proxy nb-proxy
          sleep 8
            failed_services=$(docker ps | grep Restarting | awk '{ print $NF }')
            for service in ${failed_services}
          do
            echo ""
            echo "${service} service failed to start properly:"
            echo ""
            docker logs $service
          done
          if [ -n "$failed_services" ]; then exit 1; fi

    
